ALTER TABLE users ADD COLUMN bio    TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN links  TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN banner TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN status TEXT DEFAULT 'online';
